---
title: "Spring Board Visualization Exercises"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo}
# Loading Libraries

library(ggplot2)
suppressMessages(library(dplyr))
library(ggthemes)
library(reshape2)
library(titanic)
suppressMessages(library(car))

```

##Spring Board Visualization Exercises  {.tabset .tabset-fade .tabset-pills}

### Titanic Exercise


```{r cars}
#Loading Titanic Dataset and cleaning
titanic_raw <- as.data.frame(titanic_train)
titanic_new <- titanic_raw %>% select(Survived,Pclass,Sex,Age)
str(titanic_new)
summary(titanic_new)

# cleaning up NA's by replacing with mean
titanic <- as.data.frame(titanic_new %>% 
                group_by(Sex) %>% 
                    mutate(Age = replace(Age,is.na(Age), mean(Age, na.rm = TRUE))))

# Check out the structure of titanic
str(titanic)

# Use ggplot() for the first instruction
ggplot(titanic,aes(factor(Pclass),fill = factor(Sex)))+ geom_bar(position = "dodge")


# Use ggplot() for the second instruction
ggplot(titanic,aes(factor(Pclass),fill = factor(Sex)))+ geom_bar(position = "dodge") + facet_grid(".~Survived")

# Position jitter (use below)
posn.j <- position_jitter(0.5, 0)

# Use ggplot() for the last instruction

ggplot(titanic,aes(factor(Pclass),Age,col = factor(Sex)))+ geom_jitter(position = posn.j,size=3,alpha =0.5) + facet_grid(".~Survived")


```

### CHIS exercise

```{r}

# Script generalized into a function
mosaicGG <- function(data, X, FILL) {
  
  # Proportions in raw data
  DF <- as.data.frame.matrix(table(data[[X]], data[[FILL]]))
  DF$groupSum <- rowSums(DF)
  DF$xmax <- cumsum(DF$groupSum)
  DF$xmin <- DF$xmax - DF$groupSum
  DF$X <- row.names(DF)
  DF$groupSum <- NULL
  DF_melted <- melt(DF, id = c("X", "xmin", "xmax"), variable.name = "FILL")
  library(dplyr)
  DF_melted <- DF_melted %>% 
    group_by(X) %>% 
    mutate(ymax = cumsum(value/sum(value)),
           ymin = ymax - value/sum(value))
  
  # Chi-sq test
  results <- chisq.test(table(data[[FILL]], data[[X]])) # fill and then x
  resid <- melt(results$residuals)
  names(resid) <- c("FILL", "X", "residual")

  # Merge data
  DF_all <- merge(DF_melted, resid)
  
  # Positions for labels
  DF_all$xtext <- DF_all$xmin + (DF_all$xmax - DF_all$xmin)/2
  index <- DF_all$xmax == max(DF_all$xmax)
  DF_all$ytext <- DF_all$ymin[index] + (DF_all$ymax[index] - DF_all$ymin[index])/2
  
  # plot:
  g <- ggplot(DF_all, aes(ymin = ymin,  ymax = ymax, xmin = xmin, 
                          xmax = xmax, fill = residual)) + 
  geom_rect(col = "white") +
  geom_text(aes(x = xtext, label = X),
            y = 1, size = 3, angle = 90, hjust = 1, show.legend = FALSE) +
  geom_text(aes(x = max(xmax),  y = ytext, label = FILL),
            size = 3, hjust = 1, show.legend = FALSE) +
  scale_fill_gradient2("Residuals") +
  scale_x_continuous("Individuals", expand = c(0,0)) +
  scale_y_continuous("Proportion", expand = c(0,0)) +
  theme_tufte() +
  theme(legend.position = "bottom")
  print(g)
}


# mtcars: am described by cyl
mosaicGG(mtcars,"cyl","am")

# Vocab: vocabulary described by education

mosaicGG(Vocab, "education","vocabulary")
```

